### PR TITLE
Fix panel so it works.

### PR DESCRIPTION
**Pull request by r1chardj0n3s**
Various changes needed, including:
- removed old ui-bootstrap superseded by the version included in
  Horizon
- re-jiggered heat controllers to integrate into the broader
  AngularJS application in Horizon Liberty+
- added the enabled/ files I needed to use to include the dashboard/panel
  in Horizon (I think perhaps OSA does some magic outside of this??)
- may have accidentally forced heat.js to follow the 2-space indent
  convention of Horizon...

### CODE REVIEW

**Comment by neillc** [comment]
Looks good to me

**Comment by d34dh0r53** [comment]
Hello @r1chardj0n3s and @neillc I just tested this in a liberty multinode environment and it's still not working.  I'm seeing this in my javascript console:

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:1988 Unhandled rejection Error: isEnabledTest requires both the host and hostData
    at chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:949:24
    at tryCatcher (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:5624:26)
    at Function.Promise.attempt.Promise.try (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:3069:27)
    at handleIncomingResponse (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:941:26)
    at Object.handleMessage (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:1024:19)
    at chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:854:15
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)
    at EventImpl.dispatch_ (extensions::event_bindings:371:35)
    at EventImpl.dispatch (extensions::event_bindings:393:17)
    at Event.publicClass.(anonymous function) [as dispatch] (extensions::utils:94:26)
    at dispatchOnMessage (extensions::messaging:310:22)
chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:27595 Unhandled rejection Error: isEnabledTest requires both the host and hostData
    at chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:949:24
    at tryCatcher (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:5624:26)
    at Function.Promise.attempt.Promise.try (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:3069:27)
    at handleIncomingResponse (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:941:26)
    at Object.handleMessage (chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:1024:19)
    at chrome-extension://nenlahapcbofgnanklpelkaejcehkggg/iv-shared-client-code/chrome/tab.js:854:15
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)
    at EventImpl.dispatch_ (extensions::event_bindings:371:35)
    at EventImpl.dispatch (extensions::event_bindings:393:17)
    at Event.publicClass.(anonymous function) [as dispatch] (extensions::utils:94:26)
    at dispatchOnMessage (extensions::messaging:310:22)
504f005e33bc.js:652 JQMIGRATE: Logging is active
504f005e33bc.js:1230 Error: [ng:areq] Argument 'rpc_heat' is not a function, got undefined
http://errors.angularjs.org/1.3.7/ng/areq?p0=rpc_heat&p1=not%20a%20function%2C%20got%20undefined
    at 504f005e33bc.js:699
    at assertArg (504f005e33bc.js:792)
    at assertArgFn (504f005e33bc.js:795)
    at 504f005e33bc.js:1104
    at 504f005e33bc.js:1040
    at forEach (504f005e33bc.js:705)
    at nodeLinkFn (504f005e33bc.js:1039)
    at compositeLinkFn (504f005e33bc.js:993)
    at compositeLinkFn (504f005e33bc.js:993)
    at compositeLinkFn (504f005e33bc.js:993)
    at compositeLinkFn (504f005e33bc.js:993)
    at compositeLinkFn (504f005e33bc.js:993)
    at compositeLinkFn (504f005e33bc.js:993)
    at compositeLinkFn (504f005e33bc.js:993)
    at compositeLinkFn (504f005e33bc.js:993)
    at publicLinkFn (504f005e33bc.js:985)(anonymous function) @ 504f005e33bc.js:1230
```

Thanks!

**Comment by r1chardj0n3s** [comment]
Can I get access to that environment?

**Comment by d34dh0r53** [comment]
:+1:

**Comment by d34dh0r53** [comment]
tested on AIO and multi-node and it works perfectly along with https://github.com/rcbops/rpc-openstack/pull/900

**Comment by prometheanfire** [comment]
:+1:

**Pull request merged**
